// F23 (ISS-010) — regenerate the §32 error-code catalog from the code itself.
const fs = require("fs");
const path = require("path");
const ROOT = "E:/Task Management System";

const codes = new Set();
const walk = (d) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
        const p = path.join(d, e.name);
        if (e.isDirectory()) {
            if (e.name !== "node_modules") walk(p);
        } else if (/\.ts$/.test(e.name)) {
            const s = fs.readFileSync(p, "utf8");
            for (const m of s.matchAll(/AppError\.[a-zA-Z]+\(\s*\n?\s*["']([a-z0-9_.]+)["']/g)) {
                codes.add(m[1]);
            }
        }
    }
};
walk(ROOT + "/server/src");
// codes emitted by middleware/infrastructure paths, not via AppError.<x>("code")
for (const extra of ["auth.missing_token", "auth.expired_token", "auth.invalid_token",
    "auth.rate_limited", "auth.forbidden", "validation.failed", "internal",
    "service.unavailable", "not_found"]) codes.add(extra);

const sorted = [...codes].sort();
console.log("  " + sorted.length + " distinct codes in server/src");

// group by domain prefix
const groups = new Map();
for (const c of sorted) {
    const domain = c.includes(".") ? c.split(".")[0] : "(bare)";
    if (!groups.has(domain)) groups.set(domain, []);
    groups.get(domain).push(c);
}

let table = "";
for (const [domain, list] of [...groups.entries()].sort()) {
    table += `\n**\`${domain}.*\`** — ${list.length} code(s)\n\n`;
    table += "| Code |\n|---|\n";
    for (const c of list) table += `| \`${c}\` |\n`;
}

const doc = ROOT + "/API_DESIGN.md";
const raw = fs.readFileSync(doc, "utf8");
const eol = raw.includes("\r\n") ? "\r\n" : "\n";
let s = raw.replace(/\r\n/g, "\n");

const start = s.indexOf("## 32. Error code catalog");
if (start < 0) throw new Error("§32 heading not found");
const next = s.indexOf("\n## ", start + 10);
const section = s.slice(start, next < 0 ? undefined : next);

const NEW = `## 32. Error code catalog <a id="35-error-codes"></a>

Stable string codes — the frontend can switch on these. Format: \`<domain>.<reason>\`
(a handful of infrastructure codes are bare).

> **F23 (ISS-010) — regenerated from the code, 2026-08-06.** The hand-written
> table below this note documented 37 codes while the server threw 140: a
> client written against it met over a hundred codes it had never heard of, and
> 7 documented codes were never thrown at all (several of those — \`tag.in_use\`,
> \`task.cannot_complete_blocked\`, \`sprint.overlap\`, \`role.last_admin\` on the
> legacy path — became REAL in F22). The complete list is now generated by
> \`fixing/evidence/F23/regen-catalog.cjs\` scanning every \`AppError\` call in
> \`server/src\`; re-run it after adding codes. The curated table of the most
> load-bearing codes (with meanings) follows the generated list.

### The complete set (generated)
${table}
### Curated meanings for the most load-bearing codes

| Code | HTTP | Meaning |
|---|---|---|
| \`auth.invalid_credentials\` | 401 | Email/password mismatch |
| \`auth.invalid_refresh\` | 401 | Refresh token revoked/expired |
| \`auth.rate_limited\` | 429 | Login attempts exceeded |
| \`auth.missing_token\` | 401 | No \`Authorization\` header |
| \`auth.expired_token\` | 401 | Access token past expiry |
| \`auth.forbidden\` | 403 | Permission denied for the action |
| \`validation.failed\` | 422 | Body/query failed validation. \`details[]\` lists field issues |
| \`pagination.invalid_cursor\` | 400 | A cursor this server did not issue (F23: strict round-trip) |
| \`task.not_found\` | 404 | Also any cross-workspace id (no existence oracle) |
| \`task.conflict\` | 409 | Optimistic-lock (\`If-Match\`) failure |
| \`task.archived\` | 409 | Writes frozen — comments and dependency edges included (F22) |
| \`task.cannot_complete_blocked\` | 409 | Open blockers exist (enforced since F22) |
| \`tag.in_use\` | 409 | The tag is still on tasks (enforced since F22) |
| \`sprint.overlap\` | 409 | Dates overlap another sprint (enforced since F22) |
| \`role.last_admin\` | 409 | The change would leave no active admin-capable account |
| \`space.archived\` | 409 | An archived space is frozen (F22) |
| \`space.head_invalid\` | 422 | Head must be an existing, active, non-guest member |
| \`service.unavailable\` | 503 | Pool exhaustion — retry after \`Retry-After\` seconds (F11) |
| \`internal\` | 500 | Unhandled error; \`request_id\` correlates the log line |
`;

s = s.slice(0, start) + NEW + (next < 0 ? "" : s.slice(next));
fs.writeFileSync(doc, eol === "\r\n" ? s.replace(/\n/g, "\r\n") : s);
console.log("  API_DESIGN.md §32 regenerated (" + sorted.length + " codes)");

// keep the generator with the evidence
fs.mkdirSync(ROOT + "/fixing/evidence/F23", { recursive: true });
fs.copyFileSync(__filename, ROOT + "/fixing/evidence/F23/regen-catalog.cjs");
console.log("  generator copied to fixing/evidence/F23/regen-catalog.cjs");
