#!/usr/bin/env bash
#
# Regenerates /etc/nginx/snippets/cloudflare-realip.conf from Cloudflare's
# published edge ranges.
#
#   sudo deploy/nginx/cloudflare-realip.sh && nginx -t && systemctl reload nginx
#
# WHY THIS IS NEEDED
#
# With the orange cloud on, nginx's peer is a Cloudflare edge server, so
# $remote_addr is a Cloudflare IP and every per-IP rate limit in the app
# collapses into ONE shared bucket for the whole company: the login limiter is
# 5 attempts per minute per IP, so one person mistyping their password five
# times would lock out all ~100 users. Proven in the production log, where
# requests arrived from 162.158.x.x rather than real client addresses.
#
# real_ip_header CF-Connecting-IP tells nginx to take the true client address
# from the header Cloudflare sets, but ONLY when the request actually came from
# a Cloudflare range — otherwise anyone could forge that header and bypass the
# limiters entirely. That is what set_real_ip_from enforces, and it is why this
# script pulls the current ranges rather than hardcoding them.
#
# Scoped deliberately to a snippet that our vhost includes, NOT to conf.d/:
# this box serves nine other sites and they should not silently inherit it.

set -euo pipefail

OUT=/etc/nginx/snippets/cloudflare-realip.conf
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

fetch() {
    curl -fsS --max-time 20 "$1" || {
        echo "FAILED to fetch $1" >&2
        exit 1
    }
}

{
    echo "# Generated by deploy/nginx/cloudflare-realip.sh on $(date -Is)"
    echo "# Do not edit by hand - re-run the script to refresh."
    for cidr in $(fetch https://www.cloudflare.com/ips-v4); do
        echo "set_real_ip_from ${cidr};"
    done
    for cidr in $(fetch https://www.cloudflare.com/ips-v6); do
        echo "set_real_ip_from ${cidr};"
    done
    echo "real_ip_header CF-Connecting-IP;"
} >"$TMP"

# A truncated fetch must never overwrite a good file - a short list would
# silently stop trusting some Cloudflare edges.
COUNT="$(grep -c '^set_real_ip_from' "$TMP" || true)"
if [ "$COUNT" -lt 15 ]; then
    echo "REFUSING to install: only ${COUNT} ranges parsed (expected 20+)" >&2
    exit 1
fi

mkdir -p /etc/nginx/snippets
install -m 0644 "$TMP" "$OUT"
echo "wrote ${OUT} with ${COUNT} ranges"
echo "now run: nginx -t && systemctl reload nginx"
