// =============================================================================
// Dept Review V1 — department_reports (weekly per-department HR reports)
//   Mirrors `database/schema.sql §37` 1:1.
//
// One row per (space, Dhaka-calendar week). `payload` is the full stats
// snapshot computed at generation time (shape defined by ReportStatsService —
// P18); it is REGENERATABLE (upsert on the unique key updates payload/
// generated_* only — never head_note / acknowledged_* / notified_at).
//
// `notified_at` is the atomic one-time-fanout claim: after the upsert, the
// generator runs `UPDATE … SET notified_at = ? WHERE space_id = ? AND
// week_start = ? AND notified_at IS NULL` — affectedRows=1 elects exactly ONE
// notifier, closing the weekly-job-vs-manual-generate race AND the
// "manual generate before the cron suppresses the notification" hole.
//
// `generated_at`/`notified_at`/`acknowledged_at` are APP-WRITTEN UTC (no DB
// defaults — the M8 clock-domain rule). Week dates use string mode ("YYYY-MM-DD")
// deliberately: week keys are calendar identifiers computed by the Dhaka week
// helpers, never Date objects (avoids DATE↔timezone coercion).
//
// `head_user_id`/`generated_by`/`acknowledged_by` are point-in-time SNAPSHOTS
// (deliberately no user FKs — a later role change must not rewrite history).
// The space FK is RESTRICT: reports are retained HR history — a space with
// reports can be archived forever but never hard-deleted (`SpacesService`
// surfaces `409 space.has_reports`).
// =============================================================================
import {
    bigint,
    date,
    foreignKey,
    index,
    json,
    mysqlTable,
    timestamp,
    uniqueIndex,
    varchar,
} from "drizzle-orm/mysql-core";
import { ID_LENGTH } from "./_shared";
import { workspaces } from "./auth";
import { spaces } from "./hierarchy";

export const departmentReports = mysqlTable(
    "department_reports",
    {
        id: varchar("id", { length: ID_LENGTH }).primaryKey(),
        // Keyset-cursor tie-break (composite with week_start) — never on the wire.
        internalId: bigint("internal_id", { mode: "bigint", unsigned: true })
            .notNull()
            .autoincrement(),
        workspaceId: varchar("workspace_id", { length: ID_LENGTH }).notNull(),
        spaceId: varchar("space_id", { length: ID_LENGTH }).notNull(),
        weekStart: date("week_start", { mode: "string" }).notNull(),
        weekEnd: date("week_end", { mode: "string" }).notNull(),
        /** Head snapshot at generation — NULL for headless departments (they still report). */
        headUserId: varchar("head_user_id", { length: ID_LENGTH }),
        headNote: varchar("head_note", { length: 1000 }),
        payload: json("payload").$type<Record<string, unknown>>().notNull(),
        /** NULL = generated by the automated job; else the requesting user id (snapshot). */
        generatedBy: varchar("generated_by", { length: ID_LENGTH }),
        generatedAt: timestamp("generated_at").notNull(),
        notifiedAt: timestamp("notified_at"),
        acknowledgedBy: varchar("acknowledged_by", { length: ID_LENGTH }),
        acknowledgedAt: timestamp("acknowledged_at"),
    },
    (t) => ({
        internalIdUq: uniqueIndex("uq_department_reports_internal_id").on(
            t.internalId,
        ),
        spaceWeekUq: uniqueIndex("uq_department_reports_space_week").on(
            t.spaceId,
            t.weekStart,
        ),
        wsFk: foreignKey({
            columns: [t.workspaceId],
            foreignColumns: [workspaces.id],
            name: "fk_dept_reports_ws",
        })
            .onDelete("cascade")
            .onUpdate("cascade"),
        spaceFk: foreignKey({
            columns: [t.spaceId],
            foreignColumns: [spaces.id],
            name: "fk_dept_reports_space",
        })
            .onDelete("restrict")
            .onUpdate("cascade"),
        wsWeekIdx: index("idx_department_reports_ws_week").on(
            t.workspaceId,
            t.weekStart,
        ),
    }),
);

export type DepartmentReport = typeof departmentReports.$inferSelect;
export type NewDepartmentReport = typeof departmentReports.$inferInsert;
